field: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
fieldLayouts:
  cbb24895-7233-4b99-89c8-0c02453df570:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cdda21e4-5046-411c-b78d-3ef131e76c35 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3c71015-b68a-41b6-bbc1-a14797eb1ad6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f5299e2c-41f3-4664-b39c-e119a7e9387c # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40ed2678-e2cf-491d-8252-83ec23b0fdc2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 398eea1c-c330-45d8-b628-c184e8eb94a3 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5fa01ab0-79be-4a50-bfa5-ae7420628cc2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 36e36d3b-7a46-4738-98c0-9f5eb5f6b1a0 # Button Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd7230d1-60ec-4a52-a5fb-ad50ad1a4f20
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c5a4a811-5d68-4aae-ae65-843c348bee74
        userCondition: null
fields:
  36e36d3b-7a46-4738-98c0-9f5eb5f6b1a0: # Button Url
    columnSuffix: ucbqgxoz
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonUrl
    instructions: null
    name: 'Button Url'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  398eea1c-c330-45d8-b628-c184e8eb94a3: # Button Text
    columnSuffix: rptjqeuz
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cdda21e4-5046-411c-b78d-3ef131e76c35: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Upload a rather large image with a minimum width of 1080px.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
          -
            - conditionRules
            -
              -
                __assoc__:
                  -
                    - class
                    - craft\elements\conditions\assets\WidthConditionRule
                  -
                    - uid
                    - 88f16b12-4678-4739-a15b-a81c20337b9c
                  -
                    - operator
                    - '>='
                  -
                    - value
                    - '1080'
                  -
                    - maxValue
                    - ''
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  f5299e2c-41f3-4664-b39c-e119a7e9387c: # Text
    columnSuffix: yzqnjani
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: bannerAndText
name: 'Banner and text'
sortOrder: 1
