field: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
fieldLayouts:
  9dd547c9-78a3-4ca1-ba2d-c55ac3ae74ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9e587c58-48ea-42b0-a474-68e987228fda # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8730d487-0a75-40b3-96fe-f2ecca61fe2c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8b65a32a-b14a-411c-a169-4c01fe8c5b08 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdeaa67c-f615-4bb6-9d7d-9826de4486b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6117bc72-5eb6-4b0c-8853-ea9aa0a03485 # About
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82686df2-cb2f-4e23-8381-57862514b893
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: af47fc03-50d1-4b99-9c27-d5ad7e7b3413 # Links
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46a4ed67-96b5-4696-a28e-9cd1b98d067d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c9bbbeb-dea9-4a05-8459-6211a1af5104 # Extra Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e22c8830-0d3c-41b5-866b-640c0e957398
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 681dd81b-86fe-47b9-baee-8a51ce4dec8c
        userCondition: null
fields:
  0c9bbbeb-dea9-4a05-8459-6211a1af5104: # Extra Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: extraLink
    instructions: null
    name: 'Extra Link'
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:0d091394-f7ed-4782-b499-a2e3e8e97b75' # Modular Pages
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  8b65a32a-b14a-411c-a169-4c01fe8c5b08: # Title
    columnSuffix: mrrevpic
    contentColumnType: text
    fieldGroup: null
    handle: headerTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9e587c58-48ea-42b0-a474-68e987228fda: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6117bc72-5eb6-4b0c-8853-ea9aa0a03485: # About
    columnSuffix: hwaojagl
    contentColumnType: text
    fieldGroup: null
    handle: about
    instructions: null
    name: About
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  af47fc03-50d1-4b99-9c27-d5ad7e7b3413: # Links
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: pages
    instructions: null
    name: Pages
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:0d091394-f7ed-4782-b499-a2e3e8e97b75' # Modular Pages
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: bigImageHeader
name: 'Big Image Header'
sortOrder: 8
