field: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
fieldLayouts:
  6bc9b365-7901-4416-9446-9de236c5f896:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32de1007-c8b5-4643-974a-64d929c888d0 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 841a18bf-b088-4fe1-920b-61ee2a93c922
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77577163-1b22-43a5-9e0e-5bfccb5b9fdb # Tags
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5267498-bd29-40ae-a6c2-4867b954a9af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75d8e328-49f4-4be8-b526-4258c4281f53 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90b9c6b8-0766-48da-8cb4-798713f7616d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9e054beb-e66b-47da-9f1c-e3ec067dae3a # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4686358e-1c21-447e-a476-7b8037471dda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ae2f80e-8485-4a14-b15c-7ea3170bbfa1 # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ea977f4-9832-4747-8144-e4fc2d9b19e9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d0c04ebf-b47e-4571-a633-1264da169bbe
        userCondition: null
fields:
  3ae2f80e-8485-4a14-b15c-7ea3170bbfa1: # Button Link
    columnSuffix: loakmhfo
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonLink
    instructions: null
    name: 'Button Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  9e054beb-e66b-47da-9f1c-e3ec067dae3a: # Button Text
    columnSuffix: mymvdxcm
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  32de1007-c8b5-4643-974a-64d929c888d0: # Image
    columnSuffix: kyvesusy
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  75d8e328-49f4-4be8-b526-4258c4281f53: # Text
    columnSuffix: tcujshqr
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  77577163-1b22-43a5-9e0e-5bfccb5b9fdb: # Tags
    columnSuffix: xiebevbv
    contentColumnType: text
    fieldGroup: null
    handle: tags
    instructions: null
    name: Tags
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imageBanner
name: 'Image Banner'
sortOrder: 2
