field: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
fieldLayouts:
  fb0d10cf-f26b-4bdc-9043-575e099a5f44:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ad01ffd5-6d4e-4f5c-9a0b-89e19ad53471
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 217d2050-e295-464d-8a60-0de83b6dd2d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcb0fc45-a18c-4b1e-b20b-3e434c6c44c9 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd14831c-55ac-431d-b024-0cb814be6c07
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a1b5353-3d00-41fb-8fb1-654106b70839
        userCondition: null
fields:
  ad01ffd5-6d4e-4f5c-9a0b-89e19ad53471:
    columnSuffix: hqknrskc
    contentColumnType: text
    fieldGroup: null
    handle: imagesTitle
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  bcb0fc45-a18c-4b1e-b20b-3e434c6c44c9: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: 1
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:36d3245f-b1be-4e8c-9968-66bbe04dcbee' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: images
name: Images
sortOrder: 10
