field: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
fieldLayouts:
  39e5f024-17b4-42b3-bf89-a80b0a498ec3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bfc1f3cc-23bd-4276-96aa-70145ecb622d # Rich Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 145bdf52-31f3-4f1c-b47a-fc073ee55d85
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2af881d5-3c95-4938-afbd-3d5a1c3f9094
        userCondition: null
fields:
  bfc1f3cc-23bd-4276-96aa-70145ecb622d: # Rich Text
    columnSuffix: zsydssyn
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: null
    name: 'Rich Text'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes:
        - 36d3245f-b1be-4e8c-9968-66bbe04dcbee # Images
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richTextBig
name: 'Rich Text (first letter bigger)'
sortOrder: 4
