field: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
fieldLayouts:
  99cc52c9-444b-40fe-be22-e96085f0abf9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 601ae163-99d1-46f9-858b-37589e119ab1 # Title
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef0698f7-bcfe-467e-85f4-6143f97e7c47
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b97cc793-a322-48f0-a984-237f34532a4e # Pages
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f676a09-2e2d-4604-9ee4-ed8a10b86a92
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f7892e1-5296-48d1-824d-d2827d4db709
        userCondition: null
fields:
  601ae163-99d1-46f9-858b-37589e119ab1: # Title
    columnSuffix: tgkjtnsy
    contentColumnType: text
    fieldGroup: null
    handle: titleText
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b97cc793-a322-48f0-a984-237f34532a4e: # Pages
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: pages
    instructions: null
    name: Pages
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: false
      source: null
      sources:
        - 'section:0d091394-f7ed-4782-b499-a2e3e8e97b75' # Modular Pages
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: sideMenu
name: 'side menu'
sortOrder: 11
