fieldLayouts:
  8ec5b6e0-fd0b-4c2c-bbc1-36de0e32b532:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6531a8a8-4079-4574-8db1-1eb63622d55d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b8ca1ed-9d3e-44d8-840c-99ec3f1782dc # Image
            instructions: null
            label: 'Page Banner'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e1de3c6-0c2c-4315-9e44-02b5ff234418
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f780c23-eec5-4e12-8fff-c4dc3e71bd43 # Description
            instructions: null
            label: 'Page Description'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a453e0f0-b225-470f-b426-19debc081db7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f73f028-f218-40c9-9e11-b9f9d8945125 # Blog Category
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99425558-1899-432c-988c-c6ac5b178460
            userCondition: null
            warning: null
            width: 100
        name: 'Page Settings'
        uid: 8e534f05-744f-4eb4-ae92-ccceda21d383
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dacdefa8-10bf-4e3a-8187-b0a8c18404d2 # Included In Tiny Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12fdc8b0-9208-48e9-8858-ee66feb44eb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fc7dbef-a9ec-4ba6-8e74-5b6b9320d679 # Included In Main Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4b867fb-43ba-47f9-a5fd-3279708e2396
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ff20944-75b2-45ac-91e1-307fefae9144 # Included In Footer Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 397a53d6-a9df-46ef-bbe3-22a0edbe77fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd60b55d-a074-42e5-9421-5d350544bd5b # Overwrite Level Depth
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d06ef428-47df-4571-9df1-b186f09668ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3d65eb4-6f64-4727-b7e5-f5d50c0bded9 # Secondary Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e9639f2-bd2a-439c-97d9-f6d13a004665
            userCondition: null
            warning: null
            width: 100
        name: 'Navigation Settings'
        uid: 1fce9fff-8903-451d-99ec-70bb2ee1aaf7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ed7f45e-a679-47b3-9c2e-d92af12c2e41
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3a35fae5-b990-4ea0-a708-a69527346f73
        userCondition: null
handle: blog
hasTitleField: true
name: Blog
section: 0d091394-f7ed-4782-b499-a2e3e8e97b75 # Modular Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
