fieldLayouts:
  6d592217-97c0-4e2e-81a9-70dfd7c56536:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 355d941b-6a62-4871-9d16-430aac5d57fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54d6ff96-9d67-4440-aa17-5cc191c31944
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbb6d9b5-c1d2-43d3-8518-cca6eb098634
        userCondition: null
handle: column
hasTitleField: true
name: Column
section: 0d091394-f7ed-4782-b499-a2e3e8e97b75 # Modular Pages
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
