fieldLayouts:
  6d592217-97c0-4e2e-81a9-70dfd7c56536:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 355d941b-6a62-4871-9d16-430aac5d57fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54d6ff96-9d67-4440-aa17-5cc191c31944
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbb6d9b5-c1d2-43d3-8518-cca6eb098634
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dacdefa8-10bf-4e3a-8187-b0a8c18404d2 # Included In Tiny Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2eaad558-b6fe-4318-8059-50f75db078a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fc7dbef-a9ec-4ba6-8e74-5b6b9320d679 # Included In Main Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 975aa3ec-61c6-4cb2-a517-eb346a5d6ce5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ff20944-75b2-45ac-91e1-307fefae9144 # Included In Footer Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f797f03-7de8-495b-a488-70a9b38742bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd60b55d-a074-42e5-9421-5d350544bd5b # Overwrite Level Depth
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 326b4283-1edf-4eac-9bea-f916a8bd6e37
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3d65eb4-6f64-4727-b7e5-f5d50c0bded9 # Secondary Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0920b939-ab73-41b3-8767-b1fbed5c4936
            userCondition: null
            warning: null
            width: 100
        name: 'Navigation Settings'
        uid: 8a67d615-2626-462b-942a-71bc3d4f7456
        userCondition: null
handle: column
hasTitleField: true
name: Column
section: 0d091394-f7ed-4782-b499-a2e3e8e97b75 # Modular Pages
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
