fieldLayouts:
  f564c009-fa6f-4a83-9b09-762b198a48d8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d16e5485-816f-4acc-82cc-11dca0c996ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ab02d1a4-b342-4861-8ca8-eca778042961 # External Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddff111a-cdac-4d6f-9803-ffc8ac630968
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b8ca1ed-9d3e-44d8-840c-99ec3f1782dc # Image
            instructions: null
            label: Icon
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e22a868-60ef-4769-82c1-f9c88806b045
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2d64262c-77da-4d13-9e5a-b2f5f9d48f7e
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: c65369b0-f49d-4bc9-8947-a1dd757dcc55 # Socials
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
