fieldLayouts:
  e3f1fbf9-fd2d-4310-b8d5-53574c667ca4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cb360d30-85cd-4a61-a15b-4b56a46256bb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 912049d1-af68-4d78-ac7e-373f64619bc0
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: d38472d8-ce88-4da6-b971-c5e141f59a67 # Blogs
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
