fieldLayouts:
  a6270b02-95ad-4793-bea7-c49922d73ad0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d83dc2cb-7836-453b-bc1c-241fc5002114
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34d97f74-3496-474c-89fc-62a0b42fa430
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 600904f9-244e-4842-a38a-4279db7b0930
        userCondition: null
handle: grid
hasTitleField: true
name: Grid
section: 0d091394-f7ed-4782-b499-a2e3e8e97b75 # Modular Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
