fieldLayouts:
  a6270b02-95ad-4793-bea7-c49922d73ad0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d83dc2cb-7836-453b-bc1c-241fc5002114
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34d97f74-3496-474c-89fc-62a0b42fa430
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 600904f9-244e-4842-a38a-4279db7b0930
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dacdefa8-10bf-4e3a-8187-b0a8c18404d2 # Included In Tiny Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d67884f4-8ef5-4b6b-9dfc-7949fd61347b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0fc7dbef-a9ec-4ba6-8e74-5b6b9320d679 # Included In Main Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5556a1cb-24bf-486c-b212-9eaf6ab03dd7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ff20944-75b2-45ac-91e1-307fefae9144 # Included In Footer Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7afee6d5-5a6b-4bb1-82ec-25483839ceaa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dd60b55d-a074-42e5-9421-5d350544bd5b # Overwrite Level Depth
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 81189412-f14b-4724-a685-d6b20997a010
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c3d65eb4-6f64-4727-b7e5-f5d50c0bded9 # Secondary Page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1225ee6-3480-43e6-8ef3-10ba8f86c612
            userCondition: null
            warning: null
            width: 100
        name: 'Navigation Settings'
        uid: 0ee1149a-00cc-481d-a189-b5375a5ab89c
        userCondition: null
handle: grid
hasTitleField: true
name: Grid
section: 0d091394-f7ed-4782-b499-a2e3e8e97b75 # Modular Pages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
