fieldLayouts:
  c3dc6896-b36c-4400-9c30-226d564ee0b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc982017-bb01-4a06-b6b1-455b06dedad6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f780c23-eec5-4e12-8fff-c4dc3e71bd43 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 996929bb-fd93-4368-9a27-fab508e88cef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 922b91bf-05dd-43f2-9505-8f2494af7cf0
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 1542fba4-ab16-40d2-b7c5-dc3c5606c161 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
