fieldLayouts:
  c3dc6896-b36c-4400-9c30-226d564ee0b5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cc982017-bb01-4a06-b6b1-455b06dedad6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 627d9316-0912-46e5-9fbc-5897249c7779 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5af17ff-dbd9-431a-a1ed-1cb76cd8bbd8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 922b91bf-05dd-43f2-9505-8f2494af7cf0
        userCondition: null
handle: home
hasTitleField: true
name: Home
section: 1542fba4-ab16-40d2-b7c5-dc3c5606c161 # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: language
