baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'The White House'
primary: true
siteGroup: c473eca2-49ef-44f4-9454-b7cb1cffa330 # Craft White House
sortOrder: 1
