columnSuffix: qhoinnua
contentColumnType: string
fieldGroup: e1e48183-239e-4251-8559-626b99e9336c # Common
handle: dynamiccontent
instructions: null
name: Content
searchable: false
settings:
  contentTable: '{{%matrixcontent_dynamiccontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
