columnSuffix: null
contentColumnType: string
fieldGroup: e1e48183-239e-4251-8559-626b99e9336c # Common
handle: translationsConnectForm
instructions: null
name: 'Translations Connect Form'
searchable: false
settings:
  contentTable: '{{%matrixcontent_translationsconnectform}}'
  maxBlocks: 1
  minBlocks: 1
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
