fieldLayouts:
  b0ecfd69-674d-470c-9652-6f956261d5ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d6b7f03-afd5-40de-8d15-84bd795db091 # Logo: Primary Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d3918be-e37e-413b-b955-7a82a7806262
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: edacf0d0-f17c-425b-971c-a992f1bda244 # Logo: Primary Lined
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ec453b4-b0fc-4660-b039-933de5208144
            userCondition: null
            warning: null
            width: 100
        name: Primary
        uid: 1f57ec70-dea5-4d13-bc53-a52cc00adce8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b1148404-3272-4249-ad35-fe02e4097a71 # Logo: Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8edb58a0-bde8-463b-89ba-860be4bf2ebb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 982ea9f6-3838-4aa0-8b72-b48ef98a4c8d # Logo: Min-Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5af898bb-f611-4629-a3e4-038fedc24fb6
            userCondition: null
            warning: null
            width: 100
        name: 'Text Variant'
        uid: 604ac580-e174-4850-bb12-3463d66a7196
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2c4c9376-7a0e-4de6-857d-2f27434b77c7 # Background: House
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e490b4a-b8a8-4b3a-978d-0c6779ad16c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3cd8ddfe-3329-4536-9215-a271721f301c # Background: Seal
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb03e4dd-a67c-49bb-925e-e1f025d5e2a7
            userCondition: null
            warning: null
            width: 100
        name: Backgrounds
        uid: 96c68726-f6d5-499e-b85b-5f7046af1d2e
        userCondition: null
handle: branding
name: Branding
sortOrder: 1
