fieldLayouts:
  b0ecfd69-674d-470c-9652-6f956261d5ac:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 982ea9f6-3838-4aa0-8b72-b48ef98a4c8d # Logo Main
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5af898bb-f611-4629-a3e4-038fedc24fb6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c4c9376-7a0e-4de6-857d-2f27434b77c7 # Logo Secondary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e490b4a-b8a8-4b3a-978d-0c6779ad16c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: edacf0d0-f17c-425b-971c-a992f1bda244 # Logo Side
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ec453b4-b0fc-4660-b039-933de5208144
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b1254c70-8640-4f80-bbd9-4c126fcf2b2d # Background Main Menu
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74bc0d44-3f8a-49d7-931b-6f5b7b5d9210
            userCondition: null
            warning: null
            width: 100
        name: Branding
        uid: 637f09b5-6280-4c63-9528-8f61ced1b388
        userCondition: null
handle: branding
name: Branding
sortOrder: 1
