fieldLayouts:
  d3a87d25-1a3e-45f6-b51a-d69908975386:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c0b3a23c-e48b-46a9-a84b-5cd35fcc16c9 # Blog Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3187fd14-3470-4f99-add0-b2f52871a8db
            userCondition: null
            warning: null
            width: 100
        name: Blog
        uid: 88ab0aa2-6fc2-498b-be86-332362b1c82a
        userCondition: null
handle: staticVariables
name: 'Static Variables'
sortOrder: 3
